# Generated by Django 5.2.17 on 2026-08-17 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel_transition',
            field=models.CharField(choices=[('slide', 'Slide'), ('fade', 'Fade'), ('bubble', 'Bubble'), ('none', 'None')], default='slide', max_length=10),
        ),
        migrations.CreateModel(
            name='StorageDeletionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bucket', 'object_key'), name='storage_delete_unique_object')],
                'indexes': [models.Index(fields=['completed_at', 'created_at'], name='posts_stora_complet_a2391b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('video', 'Vídeo')], max_length=10)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Lista'), ('failed', 'Fallida')], default='pending', max_length=10)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('private_object_key', models.CharField(blank=True, max_length=500, null=True)),
                ('public_object_key', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=1000)),
                ('private_poster_key', models.CharField(blank=True, max_length=500, null=True)),
                ('public_poster_key', models.CharField(blank=True, max_length=500, null=True)),
                ('poster_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('upload_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['post', 'state', 'position'], name='posts_postm_post_id_f322e8_idx'), models.Index(fields=['state', 'upload_expires_at'], name='posts_postm_state_fca9c7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('position__isnull', False)), fields=('post', 'position'), name='post_media_unique_active_position'), models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('post',), name='post_media_one_cover'), models.CheckConstraint(condition=models.Q(('is_cover', False), ('position__isnull', False), _connector='OR'), name='post_media_cover_requires_position')],
            },
        ),
    ]
