# Generated by Django 5.2.17 on 2026-08-19 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_carousel_transition_storagedeletiontask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=220)),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('visit_date', models.DateField()),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('hit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['visit_date', 'path'], name='posts_publi_visit_d_c9a4a3_idx'), models.Index(fields=['ip_address', 'visit_date'], name='posts_publi_ip_addr_de4a9e_idx'), models.Index(fields=['last_seen_at'], name='posts_publi_last_se_c3b571_idx')],
                'constraints': [models.UniqueConstraint(fields=('path', 'ip_address', 'visit_date'), name='public_visit_unique_day')],
            },
        ),
    ]
